map-tokens: 1024
model: ollama_chat/qwen2.5-coder:14b-instruct-q8_0

code-theme: gruvbox-dark

gitignore: false
attribute-author: false
attribute-committer: false

check-update: false
show-release-notes: false
