openai-api-base: http://localhost:1337/v1/
openai-api-key: lol

model: openai/qwen-2.5-coder
cache-prompts: true

light-mode: true
code-theme: solarized-light

gitignore: false

check-update: false
show-release-notes: false

notifications: true
