openai-api-base: http://localhost:1337/v1/
openai-api-key: lol

model: openai/qwen-2.5-coder

code-theme: gruvbox-dark

gitignore: false
attribute-author: false
attribute-committer: false

check-update: false
show-release-notes: false
