# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#group_imports
#group_imports = "StdExternalCrate"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity
#imports_granularity = "Crate"
