[profile.dev]
split-debuginfo = "packed"
strip = "none"
lto = "off"
panic = "unwind"

[profile.release]
strip = "symbols"
lto = "thin"
panic = "abort"

[target.x86_64-unknown-linux-gnu]
# https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
rustflags = "-C target-cpu=x86-64-v3"
