[registries.crates-io]
protocol = "sparse"

[profile.dev]
debug = "line-tables-only"

[profile.dev.build-override]
debug = false
opt-level = 3

[profile.dev.package."*"]
debug = false
opt-level = 3

[profile.debugging]
inherits = "dev"
debug = true

[profile.release]
codegen-units = 1
