[registries.crates-io]
protocol = "sparse"

[profile.dev.build-override]
debug = false
opt-level = 3

[profile.dev.package."*"]
debug = false
opt-level = 3

[profile.dev]
strip = "none"
lto = "off"
panic = "unwind"

[profile.release]
strip = "symbols"
lto = "thin"
panic = "abort"
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
rustflags = "-C target-cpu=x86-64-v3"

[target.aarch64-apple-darwin]
rustflags = "-C target-cpu=native"
