[profile.dev]
lto = false
strip = false
panic = "unwind"

[profile.release]
lto = true
strip = true
panic = "abort"

# target-cpu -> elfx86exts target/*/${binary}
# link-arg   -> readelf -p .comment target/*/${binary}
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=-fuse-ld=lld",
]
