[profile.dev]
lto = false
strip = false
panic = "unwind"

[profile.release]
lto = true
strip = true
panic = "abort"

# readelf -p .comment target/*/${binary_name}
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]
