[registries.crates-io]
protocol = "sparse"

[profile.dev]
debug = "line-tables-only"
strip = "none"
lto = "off"
panic = "unwind"

[profile.dev.build-override]
debug = false
opt-level = 3

[profile.dev.package."*"]
debug = false
opt-level = 3

[profile.debugging]
inherits = "dev"
debug = true

[profile.release]
strip = "symbols"
lto = "thin"
panic = "abort"
codegen-units = 1
