[profile.dev]
lto = "off"
strip = "none"
panic = "unwind"

[profile.release]
lto = "thin"
strip = "symbols"
panic = "abort"

# target-cpu -> elfx86exts target/*/${binary}
# link-arg   -> readelf -p .comment target/*/${binary}
[build]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=-fuse-ld=lld",
]
