#! /usr/bin/env bash
set -eu

# keep sessions
TO_DELETE=(
    ".continuerc.json"
    ".diffs"
    ".migrations"
    ".utils"
    "config.ts"
    "dev_data"
    "index"
    "package.json"
    "tsconfig.json"
    "types"
)

for f in "${TO_DELETE[@]}"; do
    echo "[93m>>> [94m${f}[0m"
    rm -rf "${f}"
done
