[user]
name = "Gabriel Linder"
email = "linder.gabriel@gmail.com"

[signing]
backend = "gpg"
behavior = "own"
key = "5FA837672AC41AE3"

[ui]
default-command = "log"
diff-formatter = "delta"
diff-editor = ":builtin"
merge-editor = ":builtin"
bookmark-list-sort-keys = ["committer-date-"]
tag-list-sort-keys = ["author-date-"]

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
