#! /usr/bin/env bash

alias dt="diffstat -C"
alias g="links https://www.google.com/"
alias grep="grep --color=auto"
alias h="history"
alias https="http --verify=no"
alias j="jobs -l"
alias l="ls -a"
alias ll="ls -al"
alias maxima="rlwrap maxima"
alias p="procs"
alias r="glow README.md"
alias rcli="redis-cli"
alias sbcl="rlwrap sbcl"
alias sc="shellcheck -f gcc"
alias show="open -a Preview"
alias t="tree"

