#! /usr/bin/env bash

alias ds="diffstat -C"
alias dt="difft"
alias grep="grep --color=auto"
alias h="history"
alias https="http --verify=no"
alias ig="ig --theme light"
alias j="jobs -l"
alias l="lsd -a"
alias ll="lsd -al"
alias maxima="rlwrap maxima"
alias p="procs"
alias r="glow README.md"
alias sbcl="rlwrap sbcl"
alias sc="shellcheck -f gcc"
alias show="open -a Preview"
alias t="tree"

