#! /usr/bin/env bash

klog() {
    pod="$1"
    shift
    containers="$*"
    if [ -z "${pod}" ] || [ -z "${containers}" ]; then
        echo "Usage: klog pod container{1..3}"
    else
        xpanes -c "kubectl logs ${pod} --follow --tail 10 -c {}" ${containers}
    fi
}

alias klogs="klog"

ktop() {
    pod="$1"
    watch -n 1 kubectl top pod --containers ${pod}
}

kpods() {
    if [ -z "${1:-}" ]; then
        kubectl get pods
    else
        watch -n 1 kubectl get pods
    fi
}
