#! /usr/bin/env bash

export LIBVIRT_DEFAULT_URI='lxc:///'

enter()
{

    guest="${1:-}"
    if [ -z "${guest}" ]; then
        echo 1>&2 "Usage: enter guestname"
        return
    fi

    guest=$(dig +short @192.168.122.1 "${guest}")
    if [ -z "${guest}" ]; then
        echo 1>&2 "Unknown guest: ${1}"
        return
    fi

    ssh "root@${guest}"

}
