#! /usr/bin/env bash

mongo_shell()
{

    if [ -f "$1" ]; then
        uri="$(cat "$1")"
    else
        uri="$1"
    fi

    if [[ "$uri" =~ "ssl" ]]; then
        mongo --shell --ssl --sslAllowInvalidCertificates "$uri"
    else
        mongo --shell "$uri"
    fi

}
