#! /usr/bin/env bash

alias v='. ./.venv/bin/activate'

_venv_ensure_base_packages() {
    pip="${1:-pip}"
    if [ -z "${VIRTUAL_ENV}" ] && [ "${pip}" = "pip" ]; then
        echo 1>&2 "Not in a virtual environment"
        return 1
    fi
    # handle eventual constraints
    if [ -f "constraints.txt" ]; then
        constraints="-c constraints.txt"
    else
        # shellcheck disable=SC2034
        constraints=""
    fi
    for package in pip wheel setuptools packaging build cython; do
        # shellcheck disable=SC2086
        "${pip}" install -U "${package}" ${=constraints}
    done
}

mkvenv() {
    version="${1:-}"
    name="${2:-}"
    if [ -z "${version}" ]; then
        echo 1>&2 "Usage: mkvenv version [name]"
        return 1
    fi
    if [ -z "${name}" ]; then
        name=".venv"
        echo 1>&2 "Creating an anonymous virtual environment in ${name}"
    else
        echo 1>&2 "Creating a virtual environment in ${name}"
    fi
    bin="python${version}"
    if [ ! "$(type "${bin}")" ]; then
        echo 1>&2 "${bin} not found"
        return 1
    fi
    if [ -d "${name}" ]; then
        echo 1>&2 "${name} already exists"
        return 1
    fi
    "${bin}" -m venv --prompt "$(basename "$(pwd)")" "${name}"
    pip="${name}/bin/pip"
    if [ ! -x "${pip}" ]; then
        echo 1>&2 "${pip} not found"
        return 1
    fi
    _venv_ensure_base_packages "${pip}" || return 1
    echo "${name} is ready"
}

upvenv() {
    _venv_ensure_base_packages || return 1
    # handle eventual constraints
    if [ -f "constraints.txt" ]; then
        constraints="-c constraints.txt"
    else
        # shellcheck disable=SC2034
        constraints=""
    fi
    # handle eventual requirements
    if [ -f "requirements.txt" ]; then
        # shellcheck disable=SC2086
        pip install -U ${=constraints} -r requirements.txt
    fi
    if [ -f "pyproject.toml" ]; then
        deps=$(yq -p toml -o json -r '.project.dependencies[]' pyproject.toml)
        if [ -n "$deps" ]; then
            # shellcheck disable=SC2086
            pip install -U ${=constraints} ${=deps}
        fi
    fi
    # update everything without consideration for broken dependencies
    while read -r p; do
        # shellcheck disable=SC2086
        pip install --no-warn-conflicts ${=constraints} -U "$p"
    done < <(pip list --outdated --format json | jq -r '.[].name')
    # handle broken dependencies
    for n in {0..9}; do
        x=0
        while read -r p; do
            [ "$p" = "No" ] && break
            # shellcheck disable=SC2086
            pip install --no-warn-conflicts ${=constraints} -U "$p"
            ((x+=1))
        done < <(pip check | awk '{print $1}' | sort | uniq)
        [ "$x" -eq 0 ] && break
    done
    # did it work ?
    if [ "$n" -eq 9 ]; then
        echo 1>&2 "[91mError: Direct intervention is necessary.[0m"
        return 1
    fi
    # we are up to date
    echo "${VIRTUAL_ENV##*/} is ready"
}

spvenv() {
    _venv_ensure_base_packages || return 1
    pip install -U \
        envdir python-dotenv \
        pipdeptree pip-upgrader pip-tools \
        flake8 isort black bandit radon \
        pydocstyle pydoclint interrogate \
        mypy vulture perflint ruff \
        ipython ipdb bpython ptpython \
        python-lsp-server pylsp-mypy python-lsp-isort python-lsp-black \
        pretty-errors
}

flvenv() {
    _venv_ensure_base_packages || return 1
    pip install -U \
        flake8 \
        flake8-bugbear \
        flake8-builtins \
        flake8-commas \
        flake8-comprehensions \
        flake8-isort \
        flake8-logging-format \
        flake8-quotes \
        flake8-return \
        flake8-simplify \
        flake8-unused-arguments \
        flake8-use-fstring
}

nbvenv() {
    _venv_ensure_base_packages || return 1
    pip install -U \
        notebook \
        ipywidgets
}

pyleaves() {
    pipdeptree -j \
        | jq -r '[.[].package.package_name] - [.[].dependencies[].package_name] | .[]'
}

clpy() {
    find -L . \
         -not -path './.git/*' \
      -a -not -path './.venv/*' \
      -a \( \
            -iname __pycache__   -print0 \
         -o -iname '*.py[co]'    -print0 \
         -o -iname .mypy_cache   -print0 \
         -o -iname .pytest_cache -print0 \
         -o -iname .ruff_cache   -print0 \
         -o -iname .hypothesis   -print0 \
         -o -iname .coverage     -print0 \
         -o -iname .tox          -print0 \
         -o -iname report.html   -print0 \
         -o -iname tags          -print0 \
    \) | xargs -r0 rm -rf --
}
