#! /usr/bin/env bash

terraform_clean() {
    find . -name .terraform | while read -r f; do
        rm -rf "./$f/"
    done
}

alias tfc="terraform_clean"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfo="terraform output | bat -l sh"
alias tfv="terraform version"
