#! /usr/bin/env bash

export PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'

show_command_in_title_bar()
{
    case "$BASH_COMMAND" in
        *\033]0*)
            ;;
        *)
            echo -ne "\033]0;${USER}@${HOSTNAME}: ${BASH_COMMAND}\007"
            ;;
    esac
}

trap show_command_in_title_bar DEBUG
