#! /usr/bin/env bash

reset_term_title() {
    print -n "\e]0;zsh\a"
}

set_term_title() {
    print -n "\e]0;${1}\a"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd reset_term_title
add-zsh-hook preexec set_term_title
