#! /usr/bin/env bash

export PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'

show_command_in_title_bar()
{
    # shellcheck disable=SC1001
    case "${BASH_COMMAND}" in
        *\033]0\;*)
            ;;
        *)
            local cmd
            printf -v cmd "%q" "${BASH_COMMAND}"
            echo -ne "\033]0;${USER}@${HOSTNAME}: ${cmd//\\/}\007"
            ;;
    esac
}

if [ -z "${SSH_CONNECTION:-}" ]; then
    trap show_command_in_title_bar DEBUG
fi
