#! /usr/bin/env bash

kv_get() {
    if [ -z "${1:-}" ]; then
        echo 1>&2 "Usage:"
        echo 1>&2 "  kv_get path/to/key"
        echo 1>&2 "  kv_get path/to/key#field"
        return 1
    fi
    IFS='#' read -r k f <<< "$1"
    if [ -z "$f" ]; then
        vault kv get "$k"
    else
        vault kv get --field="$f" "$k"
    fi
}

kv_put() {
    if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
        echo 1>&2 "To put raw values:"
        echo 1>&2 "  kv_put path/to/key#field value"
        echo 1>&2 "  echo value | kv_put path/to/key#field -"
        echo 1>&2 "  kv_put path/to/key#field @filename"
        echo 1>&2 ""
        echo 1>&2 "To put base64 encoded values:"
        echo 1>&2 "  base64 -w 0 < filename | kv_put path/to/key#field -"
        return 1
    fi
    IFS='#' read -r k f <<< "$1"
    v="$2"
    if vault kv get "$k" >/dev/null 2>&1; then
        echo 1>&2 "Updating existing secret"
        vault kv patch -method=patch "$k" "$f"="$v"
    else
        echo 1>&2 "Creating new secret"
        vault kv put "$k" "$f"="$v"
    fi
}
