#! /usr/bin/env bash

vimgrep() {
    rg -.Sl "$1" | tr '\n' '\0' | xargs -o0 vim -c "/${1//\//\\/}" --
}

vimfind() {
    fd -Ht f "$1" | tr '\n' '\0' | xargs -o0 vim --
}

vman() {
    if [ $# -eq 0 ]; then
        echo "Usage: vman <manpage>"
        return 1
    fi
    man "$1" | col -b | vim -RMc 'setf man' -
}

