#! /usr/bin/env bash

vimgrep() {
    files=()
    while IFS= read -d $'\0' -r file; do
        files+=("$file")
    done < <(grep --exclude-dir='.git' -lZir "$1")
    vim -c "/${1//\//\\/}" -- "${files[@]}"
}

vimfind() {
    files=()
    while IFS= read -d $'\0' -r file; do
        files+=("$file")
    done < <(find . -type f -not -path '.git*' -iname "$1" -print0)
    vim -- "${files[@]}"
}
