#! /usr/bin/env bash

_primary() {
    xrandr | grep -w primary | awk '{print $1}'
}

_secondary() {
    xrandr | grep -w connected | tail -1 | awk '{print $1}'
}

_check() {
    if [ "$(_secondary)" == "$(_primary)" ]; then
        echo 1>&2 'No secondary screen found.'
        return 1
    fi
}

mono() {
    _check || return
    xrandr --output "$(_secondary)" --off
    ~/reset
}

dual() {
    _check || return
    xrandr --output "$(_secondary)" --right-of "$(_primary)" --auto
    ~/reset
}
