#! /usr/bin/env bash

bindkey -e

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

gitci() {
    local ci
    ci=$(git rev-parse --short HEAD 2>/dev/null)
    if [ -n "$ci" ]; then
        if [[ $ci =~ ^[0-9]+$ ]]; then
            echo "💣 %F{red}%B$ci%b%f "
        fi
    fi
}

gitbr() {
    local br
    br=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
    if [ -n "$br" ]; then
        if [ "$br" = "HEAD" ]; then
            echo "💥 %F{red}%B$br%b%f"
        else
            echo "🌵 %F{yellow}$br%f"
        fi
    fi
}

awsp() {
    if [ -n "$AWS_PROFILE" ]; then
        echo " ⛅ %F{magenta}%B$AWS_PROFILE%b%f"
    else
        echo ""
    fi
}

export PROMPT="%F{8}%(1j.[%j] .)%F{cyan}%D{%Y-%m-%d} %D{%H:%M:%S}%f %F{blue}%1~%f %B%(?.%F{green}✓.%F{red}✗)%f%b "
export RPROMPT="\$(gitci)\$(gitbr)\$(awsp)"

if [ -f /opt/homebrew/bin/mcfly ]; then
    eval "$(/opt/homebrew/bin/mcfly init zsh)"
    export MCFLY_DISABLE_MENU=TRUE
    export MCFLY_PROMPT=">"
    export MCFLY_FUZZY=3
fi
